### ISSUE TITLE
unable to find catalog details after pull

### ISSUE THREAD

**Issue by siva-mudiyanur** [tokern/dbcat#22]
I can see that the catalog tables are created after pull but I do not see any data within the tables, please let me know if I'm missing something here. 

Catalog db: Postgres 
Source db: Redshift

I'm also reviewing the code to figure out where the db connection is being made and data is being inserted into postgres db

```
postgres.public> SELECT t.*
                 FROM public.sources t
                 LIMIT 501
[2021-06-15 14:49:18] 0 rows retrieved in 65 ms

postgres.public> SELECT t.*
                 FROM public.tables t
                 LIMIT 501
[2021-06-15 14:52:40] 0 rows retrieved in 97 ms
```

**Comment by vrajat** [comment]
Did you use dbcat from command-line? CLI is broken. I'll fix it but I also plan to deprecate it. Can you try this code in a python CLI and then check?

    from dbcat import catalog_connection
    from dbcat.dbcat import pull
    catalog = catalog_connection(<user, hostname etc of postgres database>)
    catalog.add_source(<user, hostname of redshift database>)
    pull(catalog)

Then check these tables.

**Comment by siva-mudiyanur** [comment]
I get the following error when I try to run using the given code..[It looks like](https://github.com/tokern/dbcat/blob/9c453df3a9c8a3f1d75a9d3058dd261b513b5f08/dbcat/__init__.py#L16) we're trying to access the index while passing strings. I'm digging into the code as well to figure out the the right way to pass config.

```
File "~/site-packages/dbcat/__init__.py", line 16, in catalog_connection
    return Catalog(**config_yaml["catalog"])
TypeError: string indices must be integers
```

**Comment by siva-mudiyanur** [comment]
Got to know that we need to pass the arguments in yaml format after looking at the test file, I was able to successfully load the catalog.
