### ISSUE TITLE
Install errors with version v0.5.4

### ISSUE THREAD

**Issue by vrajat** [tokern/dbcat#27]
Hi @vrajat ..I've been getting errors when I try to update the package since the issue is fixed, am I missing something or package versions needs to be loosened up in the code? 

```
INFO: pip is looking at multiple versions of dbcat to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install amundsen-databuilder[athena,bigquery,glue,rds,snowflake]==5.2.0 and amundsen-databuilder[athena,bigquery,glue,rds,snowflake]==5.2.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    amundsen-databuilder[athena,bigquery,glue,rds,snowflake] 5.2.2 depends on mysqlclient<3 and >=1.3.6; extra == "rds"
    amundsen-databuilder[athena,bigquery,glue,rds,snowflake] 5.2.0 depends on mysqlclient<3 and >=1.3.6; extra == "rds"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict 
```

_Originally posted by @siva-mudiyanur in https://github.com/tokern/dbcat/issues/23#issuecomment-873284758_

**Comment by vrajat** [comment]
This works for me in a fresh virtual environment. Are you installing this with other packages?

**Comment by vrajat** [comment]
@siva-mudiyanur This works for me in a fresh virtual environment. Are you installing this with other packages?

**Comment by siva-mudiyanur** [comment]
turns out the issue is with mysql client which amundsen databuilder has a dependency for..I followed the solution outlined [here](https://stackoverflow.com/questions/25459386/mac-os-x-environmenterror-mysql-config-not-found) to resolve it..I was able to successfully install dbcat after resolving the issue.

**Comment by vrajat** [comment]
Thanks for the update.
