### ISSUE TITLE
Outdated documentation: cannot import name <...>

### ISSUE THREAD

**Issue by FredericoCoelhoNunes** [tokern/dbcat#29]
Hi, I'm trying to understand how to use dbcat and data-lineage with Snowflake.
I was following this guide, which was the only one I found: https://tokern.io/docs/data-lineage/example

I ran into the following errors:

* `cannot import name 'catalog_connection' from 'data_lineage'`: fixed by replacing data_lineage with dbcat, as seen in another issue.
* `cannot import name 'visit_dml_queries' from 'data_lineage.parser'`: not fixed, can't find a solution although other users report being able to run this.

Finally, could you please point me out where is an example of how to properly set up `dbcat`? I was able to do it by trial an error, running dbcat commands until I discovered the config file. The documentation in the repository's README is a bit short.

Thanks and good job!

**Comment by vrajat** [comment]
Hi. Thanks for putting in the effort to work through the out-dated documentation. I've been making major changes and waiting for the API to settle down before updating the docs. 

Can you try out the [latest version of the example](https://github.com/tokern/data-lineage/blob/v0.7.6/example.ipynb) ? 

Ideally you should not need to use dbcat at all and work with tokern/data-lineage. dbcat will get automatically installed and used by the data-lineage app.

**Comment by FredericoCoelhoNunes** [comment]
Hi, tried to run the latest version of the example, but I got the following error:

`TypeError: data_lineage.Parser.parse() argument after ** must be a mapping, not str`

I am trying to use the queries that I extracted from my Snowflake database, in the way [mentioned here:](https://tokern.io/docs/data-lineage/queries):

```
query = """
    select query_text
    from table(snowflake.information_schema.query_history())
"""

connection = snowflake.connector.connect(...)

queries = []
i = 0
with connection.cursor() as cursor:
    cursor.execute(query)
    row = cursor.fetchone()

    while row is not None:
        queries.append(row[0])
        row = cursor.fetchone()
```

Unfortunately I won't have much availability to keep testing in the following weeks, keep up the good work and thanks!

**Comment by vrajat** [comment]
The APIs have changed and they dont necessarily work together. Thanks for the encouragement. Hopefully the project will be more stable the next time you try it out.
